# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gKdI2LRRUD5Nag65nV-CsRyFij5Zn3g
"""

import math
# def solution(w,h):
#     answer = 1
#     if(w>h):
#         w,h = h,w
#     elif(w==h):
#         answer = w*h-w
#         return answer

#     if(w==1):
#         answer = 0
#     else:
#         answer = w*h - 2*w

#     return answer

def solution(w,h):
    answer = 1
    # if(w>h):
    #     w,h = h,w
    # elif(w==h):
    #     answer = w*h-w
    #     return answer

    # if(w==1):
    #     answer = 0
    # else:
    answer = w*h - (w+h-math.gcd(w,h))

    return answer